version : '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: redis:latest
  api:
    expose:
      - "5000"
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/node_modules
      - ./server:/app 
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_PASSWORD=postgres_password
  client:
    expose:
      - "3000"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - api
      - client  
